name: Linode Server Deployment

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Stop and remove containers
        run: |
          docker container stop platform customers admins auth redis postgres meilisearch nginx || true
          docker container rm platform customers admins auth redis postgres meilisearch nginx || true
          docker system prune -f || true
      - name: Run docker compose
        run: docker compose -f docker-compose.yml up -d --build --remove-orphans
